service: sheriff-labrador-captcha

frameworkVersion: "3"

configValidationMode: error

provider:
  name: aws
  region: us-east-1
  architecture: arm64
  stage: development

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: ttl
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: ttl
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

functions:
  telegram:
    runtime: python3.10
    handler: handler.telegram
    events:
      - httpApi:
          path: /webhook
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:BatchWriteItem
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:DeleteItem
        Resource:
          - Fn::GetAtt: [DynamoDBTable, Arn]
    environment:
      ENDPOINT: !GetAtt HttpApi.ApiEndpoint
      #REDIS_DSN: ${env:REDIS_DSN}
      SECRET: ${env:SECRET}
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
      DYNAMODB_TABLE:
        Ref: DynamoDBTable

  stream:
    runtime: python3.10
    handler: handler.stream
    events:
      - stream:
          type: dynamodb
          filterPattern: '{$.eventName = "REMOVE" && $.userEntity.type = "Service" && $.userIdentity.principalId = "dynamodb.amazonaws.com"}'
          arn:
            Fn::GetAtt: [DynamoDBTable, StreamArn]

    environment:
      #ENDPOINT: !GetAtt HttpApi.ApiEndpoint
      #REDIS_DSN: ${env:REDIS_DSN}
      #SECRET: ${env:SECRET}
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
      DYNAMODB_TABLE:
        Ref: DynamoDBTable

  captcha:
    runtime: provided.al2
    handler: bootstrap
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
