service: sheriff-labrador-captcha

frameworkVersion: "3"

configValidationMode: error

provider:
  name: aws
  region: us-east-1
  architecture: arm64
  stage: development

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        BillingMode: PAY_PER_REQUEST

functions:
  telegram:
    runtime: python3.10
    handler: handler.telegram
    events:
      - httpApi:
          path: /webhook
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:BatchWriteItem
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:DeleteItem
    environment:
      ENDPOINT: !GetAtt HttpApi.ApiEndpoint
      REDIS_DSN: ${env:REDIS_DSN}
      SECRET: ${env:SECRET}
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
      DYNAMODB_TABLE:
        Ref: DynamoDBTable

  captcha:
    runtime: provided.al2
    handler: bootstrap
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
