service: sheriff-labrador-captcha

frameworkVersion: "3"

configValidationMode: error

provider:
  name: aws
  region: us-east-1
  architecture: arm64
  stage: development

functions:
  telegram:
    runtime: python3.10
    handler: handler.telegram
    events:
      - http:
          path: /webhook
          method: post
          authorizer:
            identitySource: method.request.header.x-telegram-bot-api-secret-token
            identityValidationExpression: ${env:SECRET}
    environment:
      ENDPOINT: !GetAtt HttpApi.ApiEndpoint
      REDIS_DSN: ${env:REDIS_DSN}
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

  captcha:
    runtime: provided.al2
    handler: bootstrap
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-python-requirements
