service: sheriff-labrador-captcha

frameworkVersion: "3"

configValidationMode: error

provider:
  name: aws
  region: us-east-1
  runtime: python3.10
  architecture: arm64
  stage: development

functions:
  telegram:
    handler: handler.telegram
    environment:
      CAPTCHA_URL: ${env:CAPTCHA_URL}
      TEMP: !GetAtt HttpApi.ApiEndpoint
      REDIS_DSN: ${env:REDIS_DSN}
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    events:
      - http: POST /webhook
  captcha:
    handler: bootstrap
    events:
      - httpApi:
          path: /captcha
          method: get

plugins:
  - serverless-python-requirements
